% Script to fot the Logistic Regression modell using the MGVB method 

clear  % Clear all variables 
clc % Clean workspace

% Random seed to reproduce results 
rng(2020)

% Load the LabourForce dataset
labour = readData('LabourForce',...     % Dataset name
                  'Type','Matrix',...   % Store data as a 2D array (default)
                  'Intercept', true);   % Add column of intercept (default)

% Compute number of features
n_features = size(labour,2)-1;

% Create a Logistic Regression model object
Mdl = LogisticRegression(n_features,...
					    'Prior',{'Normal',[0,50]});
                          
%% Run Cholesky GVB to approximate the posterior distribution of model 
% using a multivariate normal density
Post_CGVB = MGVB(Mdl,labour,...
				'LearningRate',0.001,...  
				'NumSample',100,...        
				'MaxPatience',50,...      
				'MaxIter',2000,...       
				'GradWeight',0.4,...
				'WindowSize',30,... 
                'SigInitScale',0.04,...
				'StepAdaptive',500,...      
				'GradientMax',100,...          
				'LBPlot',true);  